### ISSUE TITLE
see the requirements

### ISSUE THREAD

**Issue by max-prokofjev** [Mattynas/CSE#22]

**Comment by JaCobbMedia** [comment]
1. Creating and using your own class, struct and enum (with flag(s), preferably).
2. Property (standard, indexed, auto-implemented) usage in struct and class.
3. Named and optional argument usage.
4. Extension method usage.
5. Reading from file.
6. Generic type usage.
7. Regex.
8. Widening and narrowing type conversions.
9. Putting data to collection, iterating through it the right way.
10. LINQ to Objects usage (methods and queries), including groupJoin.
11. Implementing some of the standard .NET interfaces (IEnumerable, IComparable, IComparer, IEquatable, IEnumerator, etc.)

http://uosis.mif.vu.lt/~vytautasa/TOP/
