### ISSUE TITLE
Login, Validation

### ISSUE THREAD

**Issue by max-prokofjev** [Mattynas/CSE#36]
0. Learn how activities and intent work in android projects(fragments too)
1. add sign in fragment or integrate 2 text fields for username and password in login page.
2. Copy login regex for validation
3. learn how web services work and how to communicate with them.
4. When login is validated, send data to the web service for login validation
5. Learn how user sessions work and how to implement them (for future functionality)

**Comment by Mattynas** [comment]
I am thinking of adding admin rights ([see more on program's funcionality doc in drive](https://docs.google.com/document/d/1oLpmFerIsMysj3EORnZz6GZKp-llH0viZOZTlEMDhAw)). Should I do it? Or leave it for later?

And can I change login regex? Like adding special characters (_-,. and etc.).

**Comment by max-prokofjev** [comment]
yep, do it. and also update doc drive that we use text recognition in android project

**Comment by max-prokofjev** [comment]
also update regex so the username cant be only numbers 😀
